apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: etl
  namespace: argo
spec:
  timezone: UTC
  schedule: "0 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 4000
  workflowSpec:
    entrypoint: extracts
    templates:
    - name: extracts
      dag:
        tasks:
        - name: twip-rds-snapshot-to-s3
          templateRef:
            name: rds-snapshot-to-s3
            template: rds-snapshot-to-s3
          arguments:
            parameters:
            - name: db
              value: twip
            - name: isCluster
              value: "true"
    - name: json-to-parquet
      volumes:
      - name: data-access-secrets
        secret:
          secretName: data-access
          defaultMode: 256
      script:
        volumeMounts:
        - name: data-access-secrets
          mountPath: /run/data-access
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /run/data-access/service-account.json
        image: gcr.io/community-gamification-283222/spark:1042e88
        #{{ required "spark image value is required" .Values.images.spark }}
        imagePullPolicy: IfNotPresent
        #{{ .Values.imagePullPolicy | default "IfNotPresent" }}
        command: [bash]
        source: |
          echo hi
