apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-etl
spec:
  entrypoint: test
  templates:
  - name: test
    dag:
      tasks:
      - name: nominal-time-hourly
        templateRef:
          name: nominal-time
          template: hourly
      - name: print-result
        template: print-result 
        depends: "nominal-time-hourly"
        arguments:
          artifacts:
          - name: timestamp
            from: "{{tasks.nominal-time-hourly.outputs.artifacts.timestamp}}"
  - name: print-result
    inputs:
      artifacts:
      - name: timestamp
        path: /tmp/timestamp
    container:
      image: busybox:stable
      command: [sh, -c]
      args: ["cat /tmp/timestamp"]
