apiVersion: "v1"
data:
  vector.toml: |
    [sinks.gcs]
    type = "gcp_cloud_storage"
    inputs = ["logs"]
    bucket = {{ .Values.dataBroker.bucket }}
    compression = "gzip"
    encoding.codec = "ndjson"
    key_prefix = {{ .Values.dataBroker.prefix }}

    [sources.logs]
    address = "0.0.0.0:8080"
    encoding = "ndjson"
    type = "http"
kind: "ConfigMap"
metadata:
  name: "dc-crawler-data-broker"
