apiVersion: "v1"
data:
  vector.toml: |
    [sinks.gcs]
    type = "gcp_cloud_storage"
    inputs = ["dc_doc"]
    bucket = {{ .Values.dataBroker.bucket | quote }}
    compression = "gzip"
    encoding.codec = "ndjson"
    key_prefix = {{ printf "%s/%s" (trimSuffix "/" .Values.dataBroker.prefix) "date=%F/hour=%H/" | quote }}
    metadata = { Content-Encoding = "" }

    [sources.dc_doc]
    address = "0.0.0.0:8080"
    encoding = "ndjson"
    type = "http"

    [sources.internal_metrics]
    type = "internal_metrics" 

    [sinks.prometheus]
    type = "prometheus_exporter"
    inputs = [ "internal_metrics" ]
    address = "0.0.0.0:9598"
kind: "ConfigMap"
metadata:
  name: dc-crawler-data-broker-{{ .Values.liveDirectory.galleryKind }}
