apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dc-crawler-worker
  labels:
    app: dc-crawler-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: dc-crawler-worker
  serviceName: dc-crawler-worker
  template:
    metadata:
      labels:
        app: dc-crawler-worker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        env:
        - name: LIVE_DIRECTORY_URL
          value: "http://dc-crawler-live-dir:8080"
        - name: TOTAL
          value: {{ .Values.worker.replicas | quote }}
        - name: DATA_BROKER_URL
          value: "http://dc-crawler-data-broker:8080"
        - name: RUST_LOG
          value: "INFO"
        command: ["sh", "-c", 'PART=${HOSTNAME##*-} worker']
        ports:
        - containerPort: 8080
      nodeSelector:
        {{ toYaml .Values.worker.nodeSelector | indent 8 }}

---

apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: dc-crawler-worker
  name: dc-crawler-worker
spec:
  ports:
    - port: 8080
  selector:
    app: dc-crawler-worker
  type: ClusterIP
  clusterIP: None
