environments:
  dev:
    secrets:
    - "envs/{{ .Environment.Name }}/data-access-secrets.yaml"
    values:
    - "envs/values.yaml"
    - "envs/{{ .Environment.Name }}/values.yaml.gotmpl"

repositories:
- name: argo
  url: "https://argoproj.github.io/argo-helm"
  #- name: argo
  #url: "https://argoproj.github.io/argo-helm"
  #- name: grafana
  #$url: "https://grafana.github.io/helm-charts"
  #- name: jupyterhub
  #url: "https://jupyterhub.github.io/helm-chart/"

helmDefaults:
  wait: true
  timeout: 60
  atomic: true
  cleanupOnFail: false
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" }}

commonLabels:
  apps: cg

releases:
- name: data-access-secrets
  chart: charts/data-access-secrets
  values:
  - secrets: 
{{ toYaml .Values.dataAccessSecrets | indent 6 }}
- name: dcinside-crawler
  chart: charts/dcinside-crawler
  values:
  - dataBroker:
      bucket: datalake-cg
      prefix: json/dcinside/document/date=%F/hour=%H/
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
    worker:
      image: gcr.io/community-gamification-283222/dcinside-crawler:6040974
      nodeSelector:
        cloud.google.com/gke-nodepool: pvm-e2-micro-pool
    liveDirectory:
      image: gcr.io/community-gamification-283222/dcinside-crawler:6040974
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
- name: argo
  namespace: argo
  chart: argo/argo
  version: 0.14.0
  needs: [ argo/argo-suppliment ]
  values:
  - singleNamespace: true
  - useDefaultArtifactRepo: true
  - artifactRepository:
      archiveLogs: true
      gcs:
        bucket: datalake-cg
        keyFormat: argo/artifacts/
        serviceAccountKeySecret:
          name: data-access
          key: "service-account.json"
  - controller:
      workflowDefaults:
        metadata:
          namespace: argo
        spec:
          volumes:
          - name: 'data-access-secrets'
            secret: 
              secretName: 'data-access'
              defaultMode: 256
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
- name: argo-suppliment
  namespace: argo
  chart: charts/argo-suppliment
  values:
  - serviceAccountName: default
