environments:
  prod:
    secrets:
    - "envs/{{ .Environment.Name }}/secrets.yaml"
    values:
    - "envs/values.yaml"
    - "envs/{{ .Environment.Name }}/values.yaml.gotmpl"
    - "envs/{{ .Environment.Name }}/images.yaml"
    - "envs/{{ .Environment.Name }}/node-selectors.yaml"
    - "envs/{{ .Environment.Name }}/external-ips.yaml"

helmDefaults:
  wait: true
  timeout: 60
  atomic: true
  skipDeps: true
  cleanupOnFail: false
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" }}

commonLabels:
  apps: comm-game

helmfiles:
- path: ./subhelmfiles/system-helmfile.yaml
  values: 
  -
{{ toYaml .Values | indent 4 }}
- path: ./subhelmfiles/monitor-helmfile.yaml
  values: 
  -
{{ toYaml .Values | indent 4 }}
- path: ./subhelmfiles/etl-helmfile.yaml
  values: 
  -
{{ toYaml .Values | indent 4 }}
- path: ./subhelmfiles/dcgle-helmfile.yaml
  values: 
  -
{{ toYaml .Values | indent 4 }}
