environments:
  dev:
    secrets:
    - "envs/{{ .Environment.Name }}/data-access-secrets.yaml"
    - "envs/{{ .Environment.Name }}/secrets.yaml"
    values:
    - "envs/values.yaml"
    - "envs/{{ .Environment.Name }}/values.yaml.gotmpl"
    - "envs/{{ .Environment.Name }}/images.yaml"

repositories:
- name: argo
  url: "https://argoproj.github.io/argo-helm"

helmDefaults:
  wait: true
  timeout: 60
  atomic: true
  cleanupOnFail: false
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" }}

commonLabels:
  apps: cg

releases:
- name: data-access-secrets
  chart: charts/data-access-secrets
  values:
  - secrets: 
{{ toYaml .Values.dataAccessSecrets | indent 6 }}
- name: dcinside-crawler
  chart: charts/dcinside-crawler
  values:
  - dataBroker:
      bucket: datalake-cg
      prefix: datalake/json/dcinside/document/
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      #resources:
        #requests:
        #  memory: "100Mi"
        #  cpu: "50m"
    worker:
      image: {{ index .Values.images "dcinside-crawler" }}
      replicas: 8
      delay: 200
      sleepDuration: 60000
      nodeSelector:
        cloud.google.com/gke-nodepool: crawler-pool
      resources:
        requests:
          memory: "10Mi"
          cpu: "150m"
    liveDirectory:
      image: {{ index .Values.images "dcinside-crawler" }}
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      #resources:
      #  requests:
      #    memory: "100Mi"
      #    cpu: "20m"
- name: crawler-node-rotator
  chart: charts/crawler-node-rotator
  values:
  - image: {{ index .Values.images "crawler-node-rotator" }}
    nodePool: crawler-pool
    lifetimeMin: 60
    podLabel: "app=dc-crawler-worker"
    maxNodeCount: 4
- name: argo
  chart: argo/argo
  version: 0.15.2
  needs: [ argo-suppliment ]
  values:
  - singleNamespace: true
  - useDefaultArtifactRepo: true
  - artifactRepository:
      archiveLogs: true
      gcs:
        bucket: datalake-cg
        keyFormat: argo/artifacts/
        serviceAccountKeySecret:
          name: data-access
          key: "service-account.json"
  - server:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
  - controller:
      workflowDefaults:
        spec:
          serviceAccountName: 'argo-workflow'
          volumes:
          - name: 'data-access-secrets'
            secret: 
              secretName: 'data-access'
              defaultMode: 256
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
- name: argo-suppliment
  chart: charts/argo-suppliment
  values:
  - serviceAccountName: argo-workflow
- name: jupyter
  installed: false
  chart: charts/jupyter
  version: 0.10.6
  values:
  - image: {{ index .Values.images "jupyter-singleuser" }}
    token: {{ .Values.jupyter.token | quote }}
    nodeSelector:
      cloud.google.com/gke-nodepool: etl-pool
    spark:
      executor:
        image: {{ index .Values.images "spark" }}
        nodeSelector:
          cloud.google.com/gke-nodepool: etl-pool
    #ingress:
      #host: jupyter.dcgle.com
- name: etl
  installed: false
  chart: charts/etl
  disableValidation: true
  needs: [ argo ]
  values:
  - images:
{{ toYaml .Values.images | indent 6 }}
