apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawler-node-rotator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crawler-node-rotator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crawler-node-rotator
subjects:
- kind: ServiceAccount
  name: crawler-node-rotator
  namespace: default


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crawler-node-rotator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]

---


apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-node-rotator
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: crawler-node-rotator
          {{- if .Values.nodeSelector }}
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
          {{- end }}
          containers:
          - name: rotator
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: NODE_SELECTOR
                value: {{ range $key, $value := .Values.nodeSelector -}} {{$key}}={{$value}} {{- end }}
              - name: NODE_LIFETIME_MIN
                value: {{ .Values.lifetimeMin | quote }}
              - name: POD_LABEL
                value: {{ .Values.podLabel | quote }}
              - name: MAX_NODE_COUNT
                value: {{ .Values.maxNodeCount | quote }}
