apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: parlai-backfill
spec:
  entrypoint: main
  # limit to one job at a time
  parallelism: 2
  templates:
    - name: main
      steps:
        - - name: dcinside-parlai-dataset-skip-non-text
            templateRef:
              name: parlai-dataset
              template: dcinside
            arguments:
              parameters:
                - name: inputPath
                  value: "gs://comm-game/datalake/orc/dcinside/document/date={{item}}/"
                - name: format
                  value: orc
                - name: skipNonText
                  value: "false"
                - name: outputPath
                  value: "gs://comm-game/datalake/parlai/dcinside/document/date={{item}}/"
            withSequence:
              # run for the 19th to the 21st
              start: "1"
              end: "5"
              format: "2021-02-%02d"
