FROM postgres:13

RUN apt update &&  \
  apt -y install curl 
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN curl -fsSL https://deb.nodesource.com/setup_15.x | bash - && \
  apt-get -y install nodejs

RUN apt -y install gcc g++ make cmake libssl-dev pkg-config

ENV PATH="/root/.cargo/bin:$PATH"

RUN cargo install sqlx-cli 

ADD Cargo.toml ./Cargo.toml
ADD model/Cargo.toml ./model/Cargo.toml
ADD server/Cargo.toml ./server/Cargo.toml

RUN mkdir -p model/src server/src && \
    echo "fn main(){}" > model/src/lib.rs && \
    echo "fn main(){}" > server/src/lib.rs && \
    cargo test --no-run && \
    rm -rf model/src/lib.rs server/src/lib.rs model server

COPY model ./model
COPY server ./server

RUN DATABASE_URL="postgres://postgres:postgres@localhost/postgres" cargo test
