repositories:
- name: ingress-nginx
  url: "https://kubernetes.github.io/ingress-nginx"

releases:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  values:
  - controller:
      metrics:
        enabled: true
      service:
        enabled: true
        type: ClusterIP
        externalIPs: 
{{ toYaml .Values.externalIPs | indent 8 }}
      nodeSelector: 
{{ toYaml .Values.nodeSelectors.alwaysOn | indent 8 }}
