apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: etl
spec:
  timezone: UTC
  schedule: "0 3 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 90000
  workflowSpec:
    entrypoint: etl
    templates:
      - name: etl
        dag:
          tasks:
            - name: nominal-time
              templateRef:
                name: nominal-time
                template: daily
            - name: dcinside-json-to-orc
              templateRef:
                name: json-to-orc
                template: json-to-orc
              depends: nominal-time
              arguments:
                parameters:
                  - name: jsonPath
                    value: {{`gs://comm-game/datalake/json/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
                  - name: orcPath
                    value: {{`gs://comm-game/datalake/orc/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
                  - name: referenceOrcPath
                    value: gs://comm-game/datalake/orc/dcinside/document/date=2021-01-16
            - name: dcinside-parlai-dataset
              templateRef:
                name: parlai-dataset
                template: dcinside
              depends: dcinside-json-to-orc
              arguments:
                parameters:
                  - name: inputPath
                    value: {{`gs://comm-game/datalake/orc/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
                  - name: format
                    value: orc
                  - name: outputPath
                    value: {{`gs://comm-game/datalake/parlai/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
            - name: dcinside-parlai-dataset-skip-non-text
              templateRef:
                name: parlai-dataset
                template: dcinside
              depends: dcinside-json-to-orc
              arguments:
                parameters:
                  - name: inputPath
                    value: {{`gs://comm-game/datalake/orc/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
                  - name: format
                    value: orc
                  - name: skipNonText
                    value: "True"
                  - name: outputPath
                    value: {{`gs://comm-game/datalake/parlai-skip-non-text/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
