apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: etl
spec:
  timezone: UTC
  schedule: "0 3 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 90000
  workflowSpec:
    entrypoint: etl
    templates:
      - name: etl
        dag:
          tasks:
            - name: nominal-time
              templateRef:
                name: nominal-time
                template: daily
            - name: dcinside-json-to-orc
              templateRef:
                name: json-to-orc
                template: json-to-orc
              depends: nominal-time
              arguments:
                parameters:
                  - name: jsonPath
                    value: {{`gs://datalake-cg/datalake/json/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
                  - name: orcPath
                    value: {{`gs://datalake-cg/datalake/orc/dcinside/document/date={{tasks.nominal-time.outputs.parameters.date}}/`}}
