apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: tantivy-rest
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tantivy-rest
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        configHash: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      containers:
      - name: "rest"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
          name: http
        env:
          - name: RUST_LOG
            value: error
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8000"
          - name: INDEX_DIR
            value: "/etc/tantivy-rest/data"
          - name: SCHEMA_FILE
            value: "/etc/tantivy-rest/schema.json"
          - name: INDEX_WRITER_MEMORY_IN_BYTES
            value: "200000000"
          - name: INDEX_WRITER_THREADS
            value: "1"
          - name: COMMIT_INTERVAL_IN_SECONDS
            value: "10"
        volumeMounts:
          - mountPath: "/etc/tantivy-rest/schema.json"
            name: config
            subPath: schema.json
          - mountPath: "/etc/tantivy-rest/data"
            name: data
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: data
          emptyDir: {}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tantivy-rest
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  clusterIP: None
