apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: json-to-parquet
spec:
  templates:
    - name: json-to-parquet
      volumes:
        - name: data-access-secrets
          secret:
            secretName: data-access
            defaultMode: 256
      inputs:
        parameters:
          - name: db
          - name: isCluster
      script:
        volumeMounts:
          - name: data-access-secrets
            mountPath: /run/data-access
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
        image: {{ required "awsCliEcsong image value is required" .Values.images.awsCliEcsong }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        command: [bash]
        source: |
          /scripts/rds-snapshot-export/rds-snapshot-export \
            -b {{ .Values.rdsExportBucket | quote }} \
            -d {{`{{inputs.parameters.db}}` | quote }} \
            -k {{ .Values.rdsExportKmsKeyArn | quote }} \
            -r {{ .Values.dataAccessRoleArn | quote }} \
            -c {{`{{inputs.parameters.isCluster}}` | quote }} \
            -p {{`{{inputs.parameters.db}}` | quote }} \
            -t "43200"
