apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: etl
  namespace: argo
spec:
  timezone: UTC
  schedule: "0 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 4000
  workflowSpec:
    entrypoint: extracts
    templates:
    - name: extracts
      dag:
        tasks:
        - name: twip-rds-snapshot-to-s3
          templateRef: 
            name: rds-snapshot-to-s3
            template: rds-snapshot-to-s3
          arguments:
            parameters:
            - name: db
              value: twip
            - name: isCluster
              value: "true"
