{{- if and (.Values.nsqadmin.enabled) (.Values.nsqadmin.autoscaling.enabled) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nsq.nsqadmin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsq.name" . }}
    helm.sh/chart: {{ include "nsq.chart" . }}
    app.kubernetes.io/component: {{ .Values.nsqadmin.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.nsqadmin.autoscaling.annotations }}
  annotations:
{{ toYaml . | trim | indent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nsq.nsqadmin.fullname" . }}
  minReplicas: {{ .Values.nsqadmin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nsqadmin.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.nsqadmin.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.nsqadmin.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
