#!/usr/local/bin/python

from pyspark.sql import SparkSession

def test_mysql_connection():
    spark = SparkSession.builder.master('local').getOrCreate()
    df = spark.read.format("jdbc").options(
        url = f"jdbc:mysql://172.17.0.1:3306",
        dbtable = "test.test",
        user = "root",
        fetchSize = "10000",
    ).load()
    assert df.collect()


test_mysql_connection()
